app = "pii-monitor"
primary_region = "fra"

[build]
  [build.args]
    ELIXIR_VERSION = "1.14.5"
    OTP_VERSION = "25.3.2.13"

[env]
  PHX_HOST = "pii-monitor.fly.dev"
  PORT = "8080"
  MONITORING_INTERVAL_MS = "10000"
  SLACK_API_TOKEN=xoxp-8715406832547-8715406833491-8735399217088-67b288415a3f5c82d4db03325088d8a1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/healthcheck"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 