app = "pii-monitor"
primary_region = "fra"

[build]
  [build.args]
    ELIXIR_VERSION = "1.14.5"
    OTP_VERSION = "25.3.2.13"

[env]
  PHX_HOST = "pii-monitor.fly.dev"
  PORT = "8080"
  MONITORING_INTERVAL_MS = "10000"
  # Variables below should be configured through fly secrets
  # SLACK_API_TOKEN = "sensitive value"
  # NOTION_API_KEY = "sensitive value"
  # OPENAI_API_KEY = "sensitive value"
  # SECRET_KEY_BASE = "sensitive value"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 